language: cpp

cache:
  - apt: true

matrix:
  include:

    - os: linux
      sudo: true
      compiler: gcc
      install:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update
        - sudo apt-get install zlib1g-dev
        - sudo pip install biopython

    - os: osx
      compiler: clang-3.7
      install:
         - pip install biopython


script:
  - make test

